name: Build Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app
        run: |
          pyinstaller --windowed run.py --collect-all mediapipe --collect-all PIL

      - name: Rename output
        run: |
          mkdir release
          cp -r dist/run release/TrickFinder-${{ matrix.os }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrickFinder-${{ matrix.os }}
          path: release/
